services:
  - type: web
    name: flashapiprod
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 10000
      - key: DEFAULT_CRS
        value: EPSG:32630
      - key: DEFAULT_PROJECT
        value: default.qgs
      - key: BASE_DIR
        value: /opt/render/project/src/data
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DEBUG
        value: false
autoDeploy: true
disk:
  name: qgis-data
  mountPath: /opt/render/project/src/data
  sizeGB: 10