services:
  - type: web
    name: flashapiprod
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    numInstances: 1
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: flashapiprod-db
          property: connectionString

databases:
  - name: flashapiprod-db
    databaseName: flashapiprod
    user: flashapiprod
    plan: starter