# render.yaml pour déploiement FLASH API PROD - Plan Gratuit

services:
  # Service principal FLASH API PROD
  - type: web
    name: flash-api-prod
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: ENABLE_PORT_10000
        value: "True"
      